language: ruby
rvm:
  - 2.2

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  

script: 
  - bundle exec jekyll build

before_deploy:
  - pip install --upgrade --user awscli
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - npm install -g gulp
  - npm install
  - gulp

deploy:
  skip_cleanup: false

env:
  global:
    secure: EXAMPLE
